name: Lint

on:
  pull_request:
    branches: 
      - develop
  push:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies for my-app
        working-directory: my-app
        run: npm install

      - name: Lint my-app
        working-directory: my-app
        run: npm run lint

      - name: Install dependencies for server
        working-directory: server
        run: npm install

      - name: Lint server
        working-directory: server
        run: npm run lint
