name: Lint

on:
  pull_request:
    branches: 
      [develop]
  push:
    branches:
      [develop]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Lint my-app
        run: cd my-app && npm run lint

      - name: Lint server
        run: cd server && npm run lint
